@startuml
title 業務フロー図 - ユーザー登録業務

|バイヤー管理者|
start
:申込書提出;
note
【ビジネスルール】
Webからの申し込みも可能
end note

|サービス提供者|
:申込書受領;

if (不備が) then (ある)

  |バイヤー管理者|
  :申込書返却;
  stop
else (ない)
  |サービス提供者|
  :CSVアップロード;
  |本システム|
  :オンライン受付;
  :ディレード登録処理;
  if () then (登録失敗)
    note right
    【ビジネスルール】
    正しい形式で入力されていない場合がエラーになる
    複数の企業を同時に登録する場合は、エラーになる行以外は登録される
    end note

    |サービス提供者|
    :登録失敗通知;
    stop
  else (登録成功)
    split
      |バイヤー管理者|
      :登録成功通知;
      stop
    split again
      |サービス提供者|
      :登録成功通知;
      stop
@enduml